### PR TITLE
preliminary draft of the email report

### PR DESCRIPTION
**Pull request by DustinKLo**

### CODE REVIEW

**Review by pymonger — CHANGES_REQUESTED** [review]
Could you include a sample of a report it generates or if it is documented on the wiki provide a link?

**Comment by DustinKLo** [comment]
> Could you include a sample of a report it generates or if it is documented on the wiki provide a link?

Snippet from the email that's generated from the job
Screen Shot 2019-06-14 at 10 50 40 AM

**Comment by DustinKLo** [comment]
Confluence documentation: https://aria.atlassian.net/wiki/spaces/ARIA/pages/6815747/AOI+Ops+Report+Email

**Comment by hookhua** [comment]
Looks good. Can you update the column ordering to be sequentially ordered as:

acqlist -> slc -> ifgcfg -> gunw

**Comment by DustinKLo** [comment]
> Looks good. Can you update the column ordering to be sequentially ordered as:
> acqlist -> slc -> ifgcfg -> gunw

@hookhua are you okay with the new column ordering?

Screen Shot 2019-06-14 at 1 51 19 PM

**Review by pymonger — APPROVED** [review]

**Pull request merged**
